version: '3.1'

services:
  web:
    container_name: apache_delta
    image: apache_eco_flow
    restart: always
    ports:
      - "80:80"
    volumes:
      - "../:/var/www/html"

  db:
    container_name: mysql_delta
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haslohaslo123
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: phpmyadmin_delta
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"

volumes:
  db-vol:
  db:
    driver: local